name: F5XC CI/CD container image
on: push
jobs:
  f5-xc-cicd-container-img-login:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Docker Login
        id: login
        run: echo ${{ secrets.F5XC_AZURECR_IO_PASSWORD }} | docker login -u ${{ secrets.F5XC_AZURECR_IO_USER }} --password-stdin ${{ secrets.F5XC_AZURECR_IO_SERVER }}
        continue-on-error: false
      - run: echo "This job's status is ${{ job.status }}."
  f5-xc-cicd-container-img-build:
    runs-on: ubuntu-latest
    needs: [ f5-xc-cicd-container-img-login ]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Docker Build
        id: build
        run: |
          pwd
          ls -la
          docker build --label project-url="${{ secrets.F5XC_AZURECR_IO_PROJECT_URL}}" --tag ${{ secrets.F5XC_AZURECR_IO_TAG }} .
        continue-on-error: false
      - run: echo "This job's status is ${{ job.status }}."
  f5-xc-cicd-container-img-push:
    runs-on: ubuntu-latest
    needs: [ f5-xc-cicd-container-img-build ]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Docker Push
        id: push
        run: docker push ${{ secrets.F5XC_AZURECR_IO_TAG }}
        continue-on-error: false
      - run: echo "This job's status is ${{ job.status }}."
  f5-xc-cicd-container-img-logout:
    runs-on: ubuntu-latest
    needs: [ f5-xc-cicd-container-img-push ]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Docker logout
        id: logout
        run: docker logout ${{ secrets.F5XC_AZURECR_IO_SERVER }}
        continue-on-error: false
      - run: echo "This job's status is ${{ job.status }}."